# name: ML Application CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-test-deploy:

#     runs-on: self-hosted

#     steps:

#       # 1. Get the latest code from GitHub
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # 2. Build Docker image
#       - name: Build Docker image
#         run: |
#           docker build -t student-performance-docker .

#       # 3. Login to AWS ECR
#       - name: Login to Amazon ECR
#         run: |
#           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
#           docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_LOGIN_URI }}

#       # 4. Tag Docker image
#       - name: Tag Docker image
#         run: |
#           docker tag student-performance-docker:latest \
#           ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

#       # 5. Push Docker image to ECR
#       - name: Push Docker image to ECR
#         run: |
#           docker push \
#           ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

#       # 6. Stop old container
#       - name: Stop old container
#         run: |
#           docker stop student-performance-container || true
#           docker rm student-performance-container || true

#       # 7. Run new container
#       - name: Run new container
#         run: |
#           docker run -d \
#           -p 5000:5000 \
#           --name student-performance-container \
#           student-performance-docker:latest

#       # 8. Test application
#       - name: Test application
#         run: |
#           sleep 5
#           curl --fail http://localhost:5000


name: ML Application CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:

  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests"
          # We will add actual tests here later

      - name: Build Docker image
        run: |
          docker build -t student-performance-docker .